language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g gulp@3.8.11
  - npm install -g typescript
  - npm install -g bower
  - bower install
  - npm install --save-dev gulp-ruby-sass
  - gem install sass
  - npm install -g generator-gulp-angular
  - npm install tsd -g
script: gulp
